spring:
  datasource:
    host: localhost
    port: 5432
    username: postgres
    password: root
    database: test
    parameter:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?${spring.datasource.parameter}